# Generated by Django 5.0.4 on 2024-05-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_promocode_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
